### ISSUE TITLE
Release a 0.8 Build

### ISSUE THREAD

**Issue by myoung34** [nicholasjackson/nomad-arm6l#1]
I came here from the nomad issue
your 0.7 binary works
Any luck on 0.8? 

Mine wouldnt build properly and I dont think this process works on 0.9+ per https://github.com/hashicorp/nomad/pull/5337

**Comment by bltavares** [comment]
@myoung34 I was able to cut a new release, would you like to give it a try and see if it works? 
https://github.com/bltavares/nomad-arm6l/releases/tag/v0.8.7-armv6l
